# Generated by Django 4.2 on 2024-02-17 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscribe', '0002_rename_subscribe_subscriber'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriber',
            name='option',
            field=models.CharField(choices=[('W', 'Weekly'), ('M', 'Monthly'), ('Y', 'Yearly')], default='W', max_length=2),
        ),
    ]
