# Generated by Django 4.2 on 2024-02-17 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscribe', '0003_subscriber_option'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscriber',
            old_name='option',
            new_name='Plan',
        ),
    ]
