# Generated by Django 5.0.3 on 2024-03-11 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscribe', '0004_rename_option_subscriber_plan'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscriber',
            old_name='Plan',
            new_name='plan',
        ),
    ]
