# Generated by Django 4.2 on 2024-02-08 19:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0004_alter_jobpost_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='expiry',
            field=models.DateField(auto_now_add=True, default=datetime.datetime(2024, 2, 8, 19, 27, 43, 413690, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
