# Generated by Django 4.2 on 2024-02-08 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0005_jobpost_expiry_alter_jobpost_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpost',
            name='expiry',
            field=models.DateField(null=True),
        ),
    ]
